In [1]:
import numpy as np

In [2]:
lending_co_data_numeric_1 = np.loadtxt("Lending-Company-Numeric-Data.csv", delimiter = ',')
print(lending_co_data_numeric_1)

# np.loadtxt lebih cepat, namun akan break apabila ada data yang tidak lengkap atau formatnya salah

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [3]:
lending_co_data_numeric_2 = np.genfromtxt("Lending-Company-Numeric-Data.csv", delimiter = ',')
print(lending_co_data_numeric_2)

# np.genfromtxt lebih lambat tapi dapat menangani data yang hilang atau tidak lengkap

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [4]:
np.array_equal(lending_co_data_numeric_1,lending_co_data_numeric_2)

True

In [5]:
lending_co_data_numeric_NAN = np.loadtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';')
print(lending_co_data_numeric_NAN)

#File Lending-Company-Numeric-Data-NAN.csv datanya tidak lengkap dan formatnya ada yang beda, jadi ketika run akan error

ValueError: could not convert string '' to float64 at row 11, column 4.

In [ ]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';')
print(lending_co_data_numeric_NAN)

#np.genfromtxt akan handle data yang hilang, di outputnya akan muncul 'nan' (Not a Number)

In [ ]:
np.set_printoptions(suppress = True, linewidth = 150)
lending_co_data_numeric_NAN = np.loadtxt("Lending-Company-Numeric-Data-NAN.csv",delimiter = ';', dtype = str)
print(lending_co_data_numeric_NAN)

#dtype=str mengatur agar semua data dibaca sebagai string (str).